### ISSUE TITLE
Templates and device repository like Tamsota?

### ISSUE THREAD

**Issue by TommySharpNZ** [openshwprojects/OpenBK7231T_App#105]
Tasmota has "templates" to let us easy setup specific devices and there is also a very nice directory of all supported devices. Do we have anything like this planned?

**Comment by btsimonh** [comment]
The 'templates' are hard coded at the moment as 'quick setup' dropdown options.
However, there is also an easier to update webapp (written as a set of Vuejs single pages) which could easily access an external source - maybe a github page or wiki - where additional 'templates' could be stored. 
If we did it as a wiki, then templates could be publicly contributed....?

**Comment by openshwprojects** [comment]
@btsimonh  this is the way, would you like to implement it? Along with device photos (so everyone know what is what) and links to Elektroda teardowns

**Comment by btsimonh** [comment]
It seems to me that the webapp provides a method of using web resources easily, and is easier to modify than the source code of the devices.  And it saves us storage in the actual device....
I'm sure that if we had a set of github wiki pages with some defined structure, we could easily read them for the data part of the 'template', and link to them for the wordy part (including links to forum teardowns, etc. - I love that part because to be able to confirm that you have the exact same device & circuit adds confidence...).
But; we'd need some buy-in from others here with the ability to code in the vuejs webapp - it's a fair platform at the moment - technically it fits but I'm not the greatest when it comes to UI!.
s

**Comment by TommySharpNZ** [comment]
Tasmota expects you to type/paste in a csv string for the template.... Which is handy for developing and testing templates but easy to stuff up for newbies... So possibly 2 options to pick from a defined list pulled from GitHub and a second advanced option to type in your own?

A repository with a page per device with photos and teardown would be very cool!

**Comment by openshwprojects** [comment]
There will be lots of teardowns, altough I first write them in polish and then translate.
Here is an example one:
https://www.elektroda.pl/rtvforum/viewtopic.php?t=3903356&highlight=
I made sure that photos are of good enough quality. Translation pending.


"Tasmota expects you to type/paste in a csv string for the template"
It should be obvious that the underlying template mechanism will be a CSV string (or something like that), with an extra templates repository available through the App

The repository should have a search function and it should be possible to look for device with multiple keywords (eg. entering the name of chip on board should filter the devices...)

**Comment by belveder79** [comment]
Just to add my 2 cents, I'm pretty excited that you've put in all that effort to make it Tasmota-like - thx a lot for that. 

To me the use of a customizable template is also key to have this firmware rolled out more widely. I recently bought a few of [those Aubess switches](https://templates.blakadder.com/unsupported/aubess_16A_mini_smart_switch.html) and ended up replacing the chip with a pin-compatible ESP on one of them, but wait for a more "plausible" solution for the others, which has arrived now thx to your efforts.

I have a [plausible configuration](http://www.arth.co.at/data/development/PinConfig-OpenBK7231N-Aubess16A.pdf) for those switches, but it is obviously tedious to apply it without a template... the other issue is that I believe that (like me) a lot of nerds are experimenting around getting it finally to work, but don't share the information in the form of a full teardown and blog entry... I think it would be great to just have a WIKI page to temporarily collect all this information to not have it lost....

**Comment by LuisThe0ne** [comment]
I personally think a Repository with some Kind of defined File-Format (like [Tasmota](https://github.com/blakadder/templates)) and a custom Frontend like [Tasmota](https://templates.blakadder.com) because that way someone would review the new templates and it is not that likely that non working or incorrect templates are made. I also already thaough about this using github pages and Blazor webassembly but wasn't sure hopw to access the Github files without downloading them.

**Comment by LuisThe0ne** [comment]
So if anyone is interested, here would be my concept for this:

A simple device Repository on GitHub (like [Tasmota](https://github.com/blakadder/templates)) with a Website built with jekyll (again like Tasmota) and somewhat of a "Install button" that asks you for a IP Address and the redirects you to the Address with some kind of argument like (?template="") and in the WebApp it would be possible to implement the same but with some kind of button event handler or so (Idk what were able to do with Vue.js) that displays the Website on a Iframe but when the Install button is clicked you don't need to enter a IP address.

**Comment by openshwprojects** [comment]
Let's say it's done, we have a database here:
https://github.com/OpenBekenIOT/webapp/blob/gh-pages/devices.json
Thank you for all your suggestions. If you have any devices, submit them here:
https://github.com/OpenBekenIOT/webapp/blob/gh-pages/devices.json
and post a teardown on Elektroda. Thanks!
