### ISSUE TITLE
Module Pin Configuration is sometimes messed up

### ISSUE THREAD

**Issue by iprak** [openshwprojects/OpenBK7231T_App#165]
I ran into this on a new BK7231N device while using Chrome

![image](https://user-images.githubusercontent.com/6459774/185102788-2e4d3c9b-49cc-465c-8c7d-c5e9321da624.png)

DOM content inspection confirmed that some options were not inside the `select` tag. Also note that option 8 is missing.
![image](https://user-images.githubusercontent.com/6459774/185102927-2e649c3c-127c-46c4-ae4a-bafc471ad1d7.png)

**Comment by pretoriano80** [comment]
Yeah,i noticed that a few times while setting up the Aubess switch.

**Comment by openshwprojects** [comment]
Which version? It was reported to me on Elektroda some time ago and I tought I have fixed it by reenabling multithreading in HTTP server (instead of handling one client at time in a blocking manner)

**Comment by iprak** [comment]
This was in 1.12.33 .. the funny thing is that it auto corrected itself. I reviewed the code and did not see see a problem with the content generation.

**Comment by openshwprojects** [comment]
I was trying to optimize memory usage for HTTP server, because the old version (and the restored version as well) does malloc and free for each request. I tried to process packets in queue, in a blocking manner and it turned out that it somehow caused this issue. This might be related to threading and/or LWIP. I have certain hunch about it.

Still, it should not happen in the current version. Does it happen in the today/yesterdays build?
