### ISSUE TITLE
How to retain current status of device after HA restarts?

### ISSUE THREAD

**Issue by ferbulous** [openshwprojects/OpenBK7231T_App#317]
Hi, I've enabled these settings in general

<img width="633" alt="image" src="https://user-images.githubusercontent.com/24526737/197304055-d3900b1b-36f9-478f-89d9-5bb3de5ad602.png">

But when I restart HA, it doesn't show the current status and I still have to toggle it first to (either from the device or from HA dashboard) to have it display the correct status

<img width="634" alt="image" src="https://user-images.githubusercontent.com/24526737/197304021-62ba7b90-b32d-4a9e-8765-50a469a348f3.png">

Is there other settings I need to enable as well?

**Comment by openshwprojects** [comment]
Hello @ferbulous , I will check this now. By the way, thanks for next teardown on Elektroda. We appreciate it. 

Let's test that on my device:
![image](https://user-images.githubusercontent.com/85486843/197323693-e8bd0798-0b6c-4de6-ae67-0f0f53347852.png)

Hmm:
![image](https://user-images.githubusercontent.com/85486843/197323548-4d113f22-3e4c-49f7-92d7-e5bca6d24a53.png)
That's strange, I did a HA restart but the device didn't get MQTT 0 even for a second..

Info:MAIN:Time 333, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 334, free 79536, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 3/38
Info:MAIN:Time 335, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 336, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 337, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 338, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 339, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 340, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38

I used this button:
![image](https://user-images.githubusercontent.com/85486843/197323603-49f408ff-da64-4e51-842f-810de573f4b3.png)

So HA didn't have device state after restart and had to wait for "publish self state every minute".

That's strange.

Anyone of devs can confirm? @valeklubomir  @btsimonh 

Ok, let's do test 2 - turn off HA VM:
![image](https://user-images.githubusercontent.com/85486843/197323633-1748223f-ba3c-43d2-8947-f2c0892d33e1.png)

device still has MQTT 1:
![image](https://user-images.githubusercontent.com/85486843/197323645-cc6757c5-40a6-45dc-ae73-9f3e62377a89.png)
Gotten time out:
![image](https://user-images.githubusercontent.com/85486843/197323670-9f695271-6af6-49ab-af85-0c084701b3dc.png)

MQTT still is 1, huh....
![image](https://user-images.githubusercontent.com/85486843/197323685-bd8cc1e2-63d3-4bbb-8a4b-0207ecc386dc.png)


Info:MAIN:Time 591, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 592, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 593, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 594, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 595, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 596, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 597, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 598, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MQTT:Publishing val 1 to obk8D38570E/led_enableAll/get retain=0
Info:MQTT:[g_bPublishAllStatesNow] item -9 result 0
Info:MAIN:Time 599, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 600, free 79536, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 3/38
Info:GEN:dhcp=0 ip=192.168.0.117 gate=192.168.0.1 mask=255.255.255.0 mac=38:1f:8d:38:57:0e 
Info:MAIN:Time 601, free 85088, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MQTT:mqtt_connection_cb: Disconnected, reason: 257(Timeout)
Info:MAIN:Time 602, free 85088, MQTT 0(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 603, free 85088, MQTT 0(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 604, free 79536, MQTT 0(1), bWifi 1, secondsWithNoPing -1, socks 3/38
Info:MAIN:Time 605, free 85088, MQTT 0(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:MAIN:Time 606, free 85088, MQTT 0(1), bWifi 1, secondsWithNoPing -1, socks 2/38

It detected disconnect after a minute or so....

Let me start HA now.
![image](https://user-images.githubusercontent.com/85486843/197323722-1b15bfe3-62c3-49d1-bdfe-9fd19c01e3e5.png)
And device got 'reconnect' , by the way HA overwrote my device state (enable) but that's not the issue now..
![image](https://user-images.githubusercontent.com/85486843/197323792-89f731fc-ac94-494f-96bb-207c3869aeac.png)


**My current conclusion is that if you do a quick restart of Home Assistant, for some reason, the MQTT doesn't discover the connection drop, which is for me surprising because TCP should know that socket was closed... and since MQTT doesn't discover the connection loss, it does not broadcast the self state "on connect" and so the next time HA gets update is after a minute when a "broadcast self state every minute" runs.**
Thoughts, @valeklubomir  ?

@ferbulous can you post the full log from OBK , starting at the moment you restart HA and ending when HA is online? I would like to see if you also have MQTT 1 all the time.

**Comment by openshwprojects** [comment]
The TCP connection of MQTT should know that it was dropped during restart and for some reason it doesn't seem to know. Maybe decreasing the allowed time out could help.

**Comment by ferbulous** [comment]
@openshwprojects 
Hi, here's a recording of the logs when HA is restarted

https://www.youtube.com/watch?v=n1yAYNctIDU

> The TCP connection of MQTT should know that it was dropped during restart and for some reason it doesn't seem to know. Maybe decreasing the allowed time out could help.

How should I adjust that in the settings?

**Comment by openshwprojects** [comment]
@ferbulous this is only available in code....

but there might be another approach - have you tried enabling 'retain' in flags?

**Comment by ferbulous** [comment]
> @ferbulous this is only available in code....
> 
> but there might be another approach - have you tried enabling 'retain' in flags?

Thanks! That fixed it

**Comment by openshwprojects** [comment]
@ferbulous  this, however, does not explain why HA restart does not send a TCP close to sockets.... but I'm happy that I helped.
