### ISSUE TITLE
Tunable white configuration.

### ISSUE THREAD

**Issue by valeklubomir** [openshwprojects/OpenBK7231T_App#386]
Device #1: LSC Smart Bulb 1400 lm/E27/Tunable White
Device is 14W tunable white, with BK7231T and simple current drivers controlled by PWM. 
PWM1 - Cold White
PWM2 - Warm White

Device #2: LED SMART WIFI Ceiling light 
Device is 28 W, 1960 lm, tunable white 3000 – 6000 K controlled by special driver BP5926. BK7231N
PWM1 - Light Intensity
PWM2 - Light Temperature

"Stupid" question. How to correctly setup this devices?

EDIT: I could "reverse" engineer code for lighting driver. But asking is faster. :-)

**Comment by openshwprojects** [comment]
Device 1 - just Channel 0 to PWM and Channel 1 to PWM and it should happen automatically? 
Device 2 - as above, but then set flag:
![image](https://user-images.githubusercontent.com/85486843/199224791-dbb74e1f-2481-4597-a972-b9969cfb4bfb.png)

**Comment by valeklubomir** [comment]
![image](https://user-images.githubusercontent.com/71550793/199233152-2f1d087d-b3eb-4fa7-8cd4-b0164a96f5ca.png)
PWM index ?  Is 0 used?  Regular users are not programmers most do not know that 0 can be used.

**Comment by openshwprojects** [comment]
The PWM index selection is smart and just checks which index is defined first. If that's 0, then 0 is used. If that's 1, then 1 is used.

**Comment by valeklubomir** [comment]
How do I setup that light correctly? After REBOOT/RESTART, I see this:
![image](https://user-images.githubusercontent.com/71550793/199289166-e692d1e4-34cd-4f6e-84ac-86221deabf2e.png)
But light is off in the real, only after changing any setting brightness or temperature light goes ON.

**Comment by openshwprojects** [comment]
@valeklubomir  I saw that, I think it's a little bug, the light is off at the start and somehow the led state seems to be 1, I will look into it tomorrow.
But basically, it should work okay if you just click "Toggle Light" twice. 
THE FIX is most likely just:
![image](https://user-images.githubusercontent.com/85486843/199318056-07767582-f06e-4c93-bf58-dee4ab84c17a.png)

changing it to 0 here. I gotta go now, I will look into it tomorrow morning (in about 14 hours at most from now) and also commit a lightweight vsnprintf
