### ISSUE TITLE
Relay does not toggle when Button and / or LED are on the same channel

### ISSUE THREAD

**Issue by kinsi55** [openshwprojects/OpenBK7231T_App#593]
**Describe the bug**
I'm encountering a weird issue right now where the relay in my plug will only toggle on if it is on its own seperate channel - If I try to put the Button and / or LED on the same channel, the button does work, the LED does turn on, but the Relay does not.

**Firmware:**
- Version 1.15.294
- Aubess 16A Plug with BL0937
- Chip/model: BK7231N

The Pins are configured correctly as all functions work (BL0937 is read correctly, LED toggles on when pressing the button, Relay turns on via Web when its on its own channel that doesnt share the button or LED)

This is my current config: 
![grafik](https://user-images.githubusercontent.com/8348306/211171533-125ecac8-75bb-42fc-9058-dee5b228afe7.png)

**Comment by openshwprojects** [comment]
Sorry, omg, fixed. Thank you for reporting. That was BAD. I will add a self test for that.

**Comment by openshwprojects** [comment]
@iprak  https://github.com/openshwprojects/OpenBK7231T_App/commit/8de7957f7d5b9414e626fc6b4f56e6a159bee1f2 please be careful more next time, I will add a self-test so it doesn't happen, but basically that condition:
![image](https://user-images.githubusercontent.com/85486843/211179649-84abfc1b-0eef-489c-b914-26721756aa20.png)
broke setting further channels due to calls being in the same loop:
![image](https://user-images.githubusercontent.com/85486843/211179654-b1f47f6d-b8f7-4759-8d3b-9824ac7339e6.png)

**Comment by kinsi55** [comment]
Confirmed fixed, thanks so much!

**Comment by iprak** [comment]
Thanks. My intention was to quit if DHT channel was found since that would be shared with anything else but I messed up the condition. Can you change it to quit in that case?
