### ISSUE TITLE
IR - Single Remote not working

### ISSUE THREAD

**Issue by glichten1** [openshwprojects/OpenBK7231T_App#657]
**Describe the bug**
IR remote with device ID "IR_NEC 0xEF00" not working. Every other IR remote control with same configuration (for Example IR_NEC 0x2) is working.

**Firmware:**
- Version 1.15.417
- Device casalux smart wlan led strip
- Chip/model: BK7231N
- Device config?

**To Reproduce**

**Screenshots**
Autoexec.bat:
![image](https://user-images.githubusercontent.com/63398783/217780765-621dbb1b-c0d3-4cbd-96e7-51f13162063f.png)
Logs
![image](https://user-images.githubusercontent.com/63398783/217781324-1433d230-2b54-408f-a48c-cca1afbd761d.png)

**Additional context**

**Comment by openshwprojects** [comment]
Hello. It looks like it might be caused by our wrong assumption that arguments are signed 16 bit integers. 
I've added a fix:
https://github.com/openshwprojects/OpenBK7231T_App/commit/c4e179229c2db26223099ac7b4729b21a912bcc5
Can you check if it works for you with this commit - get latest update when it's built.

**Comment by glichten1** [comment]
That was really quick.
It is working!
Thx
