### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by jbanaszczyk** [openshwprojects/OpenBK7231T_App#66]
https://github.com/openshwprojects/OpenBK7231T_App/blob/main/src/flash_config/flash_config.c#L146

2x `malloc` without `free`

**Comment by btsimonh** [comment]
test1 and test2?
the can be removed now - I was concerned at one point that the allocated table was being overwritten, so these are just a couple of 'guard' areas containing known data, HOPEFULLY either side of the *initial* cfg area (since it's allocated close to startup, but proximity is in no way guaranteed - so they are actually of little use!).
But in any case, they should only be allocated once at startup, and never again.

**Comment by btsimonh** [comment]
p.s. pls take a look at 
https://github.com/openshwprojects/OpenBK7231T_App/pull/67
and confirm it addresses the issues you have highlighted.

also, PRs welcome :).

I'll close the issues for now, re-open if necessary?
