### ISSUE TITLE
Inching mode for button press

### ISSUE THREAD

**Issue by sodiniss** [openshwprojects/OpenBK7231T_App#703]
I want to turn on a relay when the button is pressed and turn it off when I release the finger (think of PulseTime for tasmota, or inching). How do I do that? Thanks

**Comment by openshwprojects** [comment]
Use the dinput role, which is a digital input with some very basic debouncing.

**Comment by sodiniss** [comment]
Thanks for the quick response. It worked perfectly

**Comment by C0rn3j** [comment]
What if I want the inching feature that Tuya has - press for ON, and it will automatically toggle off after X seconds?

OP is requesting turn off after button is no longer held, which is not my use case.

I see you suggested to write a LittleFS script as `autoexec.bat` - https://www.elektroda.com/rtvforum/viewtopic.php?p=20797359#20797359

Which looks like the `Full web app -> Filesystem -> Create file` can do - is that still the way to go? It seems to work for me at least.

```c++
// This aliased command will turn off relay on Channel after 10 seconds
// addRepeatingEvent	[IntervalSeconds][RepeatsOr-1][CommandToRun]
alias turn_off_after_time_1 addRepeatingEvent 3 1 setChannel 1 0
alias turn_off_after_time_2 addRepeatingEvent 6 1 setChannel 2 0
alias turn_off_after_time_3 addRepeatingEvent 6 1 setChannel 3 0
alias turn_off_after_time_4 addRepeatingEvent 6 1 setChannel 4 0

// this will run the turn off command every time that Channel becomes 1
addChangeHandler Channel1 == 1 turn_off_after_time_1
addChangeHandler Channel2 == 1 turn_off_after_time_2
addChangeHandler Channel3 == 1 turn_off_after_time_3
addChangeHandler Channel4 == 1 turn_off_after_time_4
```

I have also later added a way to prevent the buttons for DOWN/UP to be able to turn on at the same time, as misuse managed to fry a relay in the past:

```c++
// This is not enough for some setups, see the new mutex driver if you need real mutexing:
//   https://github.com/openshwprojects/OpenBK7231T_App/issues/1701
alias turn_off_after_time_1 addRepeatingEvent 35 1 setChannel 1 0
alias turn_off_after_time_2 addRepeatingEvent 30 1 setChannel 2 0
alias turn_off_after_time_3 addRepeatingEvent 35 1 setChannel 3 0
alias turn_off_after_time_4 addRepeatingEvent 30 1 setChannel 4 0

addChangeHandler Channel1 == 1 backlog setChannel 2 0; turn_off_after_time_1
addChangeHandler Channel2 == 1 backlog setChannel 1 0; turn_off_after_time_2
addChangeHandler Channel3 == 1 backlog setChannel 4 0; turn_off_after_time_3
addChangeHandler Channel4 == 1 backlog setChannel 3 0; turn_off_after_time_4
```

EDIT: How do I cancel the script if the channel is set to 0?

I can do On, off, On, and it will still use the old timer from the first on.

EDIT2: Turns out there's examples https://github.com/openshwprojects/OpenBK7231T_App/tree/main/docs/autoexecExamples.md
