### ISSUE TITLE
Identify pins for flashing KS811 switch. (bk7231n)

### ISSUE THREAD

**Issue by kjjordans** [openshwprojects/OpenBK7231T_App#77]
Hi, 
Can you please help to identify the pins for flashing? I have not been able to find a pinout for the chip or programming header. 

![image](https://user-images.githubusercontent.com/3042340/165004130-ded3c5fd-8213-4a7c-b1f9-c268f83dacec.png)

![image](https://user-images.githubusercontent.com/3042340/165004312-04f59c86-836c-49f4-80e6-3160667bea8f.png)

**Comment by openshwprojects** [comment]
Again; I would kindly advise to keep repository Issues to issues related to our firmware, and not to generic flashing, you can ask for flashing here:

https://www.elektroda.com/rtvforum/topic3866123-480.html

but since you already asked, I have copied the pin mapping to your photo:
![image](https://user-images.githubusercontent.com/85486843/165016250-4bb88b57-d98c-485e-9145-72439235762e.png)
I think with that you can clearly see which pins are TX RX and CEN. Maybe also 3.3V, but if not, you can check for 3.3V with multimeter.
